language: rust
cache: cargo
jobs:
  include:
    - stage: tests
      cargo test --verbose
    - stage: stable
      rust:
        - stable
    - stage: beta
      rust:
        - beta
    - stage: nightly
      rust:
        - nightly
matrix:
  allow_failures:
    - stage: nightly
  fast_finish: true